// <auto-generated />
namespace FilmOverflow.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ticketSeatChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ticketSeatChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201408241639491_ticketSeatChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
